import "../styles/index.css";
import type { Metadata } from "next";
import { Mitr } from "next/font/google";

const mitr = Mitr({
  variable: "--font-mitr",
  weight: ["300", "400", "500", "600"],
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mitr.variable} font-sans font-light`}>
        {children}
      </body>
    </html>
  );
}
